# Generated by Django 2.0.7 on 2018-07-10 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='data campeonato')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bandeira', models.CharField(max_length=100)),
                ('numero_internacional', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=200)),
                ('clausula', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='data jogo')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField()),
                ('criterios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Criterio')),
            ],
        ),
        migrations.CreateModel(
            name='Regulamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Regra')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDetalhes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('numero_cartao', models.BigIntegerField()),
                ('bandeira_cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Cartao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='times',
            field=models.ManyToManyField(to='show.Time'),
        ),
        migrations.AddField(
            model_name='gol',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Jogo'),
        ),
        migrations.AddField(
            model_name='gol',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Time'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Modalidade'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='times',
            field=models.ManyToManyField(to='show.Time'),
        ),
        migrations.AddField(
            model_name='bolao',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Campeonato'),
        ),
        migrations.AddField(
            model_name='bolao',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolao',
            name='regulamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Regulamento'),
        ),
    ]
