# Generated by Django 2.0.7 on 2018-07-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regra',
            name='pontuacao',
            field=models.IntegerField(default=5),
        ),
    ]
