# Generated by Django 2.0.7 on 2018-07-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20180710_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulamento',
            name='nome',
            field=models.CharField(default='Padrão', max_length=200),
        ),
    ]
