# Generated by Django 2.0.7 on 2018-07-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20180710_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premiacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes', models.CharField(default='', max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='TiposPremiacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bolao',
            name='nome',
            field=models.CharField(default='Bolão dos Amigos', max_length=200),
        ),
        migrations.AddField(
            model_name='premiacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.TiposPremiacao'),
        ),
    ]
