# Generated by Django 2.0.7 on 2018-07-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_bolao_premicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiacao',
            name='valor',
        ),
        migrations.AddField(
            model_name='bolao',
            name='aberto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bolao',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='premiacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
