# Generated by Django 2.0.7 on 2018-07-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_auto_20180710_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolao',
            name='valor_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premiacao',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
