# Generated by Django 2.0.7 on 2018-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0010_auto_20180711_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='imagem',
            field=models.CharField(default='time_padrao.jpg', max_length=100),
        ),
    ]
