# Generated by Django 2.0.7 on 2018-07-27 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show', '0012_auto_20180721_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodetalhes',
            name='amigos',
            field=models.ManyToManyField(related_name='Amigos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bolao',
            name='imagem',
            field=models.ImageField(default='bolao_padrao.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='bolao',
            name='premicacao',
            field=models.ManyToManyField(to='show.Premiacao', verbose_name='Premiação'),
        ),
    ]
