# Generated by Django 2.0.5 on 2018-08-01 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show', '0013_auto_20180727_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacionamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito', models.BooleanField(default=False)),
                ('requerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuariodetalhes',
            name='amigos',
        ),
        migrations.RemoveField(
            model_name='usuariodetalhes',
            name='bandeira_cartao',
        ),
        migrations.RemoveField(
            model_name='usuariodetalhes',
            name='numero_cartao',
        ),
    ]
